- name: Execute the Blogpost demo tasks
  hosts: localhost
  tasks:
  - name: Download cirros image
    get_url:
      url: https://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
      dest: /home/cirros-0.3.4-x86_64-disk.img
  - name: Upload cirros image to openstack
    os_image:
      name: cirros
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /home/user/Downloads/cirros-0.3.4-x86_64-disk.img
